In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 14.5 MB/s 
     |████████████████████████████████| 6.6 MB 66.3 MB/s 
     |████████████████████████████████| 101 kB 11.1 MB/s 
     |████████████████████████████████| 596 kB 73.2 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
from transformers import TFBertForMaskedLM

In [3]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased')

All model checkpoint layers were used when initializing TFBertForMaskedLM.

All the layers of TFBertForMaskedLM were initialized from the model checkpoint at bert-large-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [4]:
from transformers import AutoTokenizer

In [5]:
tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased")

In [6]:
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf')

In [7]:
tokenizer.cls_token_id

101

In [8]:
tokenizer.sep_token_id

102

In [9]:
tokenizer.mask_token_id

103

In [10]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[ 101, 4715, 2003, 1037, 2428, 4569,  103, 1012,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [11]:
print(inputs['input_ids'])

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [12]:
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)


In [13]:
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [14]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

In [15]:
pip('Soccer is a really fun [MASK].')

[{'score': 0.7621114253997803,
  'sequence': 'soccer is a really fun sport.',
  'token': 4368,
  'token_str': 'sport'},
 {'score': 0.2034202218055725,
  'sequence': 'soccer is a really fun game.',
  'token': 2208,
  'token_str': 'game'},
 {'score': 0.012208565138280392,
  'sequence': 'soccer is a really fun thing.',
  'token': 2518,
  'token_str': 'thing'},
 {'score': 0.0018630304839462042,
  'sequence': 'soccer is a really fun activity.',
  'token': 4023,
  'token_str': 'activity'},
 {'score': 0.0013354892143979669,
  'sequence': 'soccer is a really fun field.',
  'token': 2492,
  'token_str': 'field'}]

In [16]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.2562900185585022,
  'sequence': 'the avengers is a really fun show.',
  'token': 2265,
  'token_str': 'show'},
 {'score': 0.17284077405929565,
  'sequence': 'the avengers is a really fun movie.',
  'token': 3185,
  'token_str': 'movie'},
 {'score': 0.11107708513736725,
  'sequence': 'the avengers is a really fun story.',
  'token': 2466,
  'token_str': 'story'},
 {'score': 0.07248977571725845,
  'sequence': 'the avengers is a really fun series.',
  'token': 2186,
  'token_str': 'series'},
 {'score': 0.07046651840209961,
  'sequence': 'the avengers is a really fun film.',
  'token': 2143,
  'token_str': 'film'}]

In [17]:
pip('I went to [MASK] this morning.')

[{'score': 0.3573071360588074,
  'sequence': 'i went to work this morning.',
  'token': 2147,
  'token_str': 'work'},
 {'score': 0.23304428160190582,
  'sequence': 'i went to bed this morning.',
  'token': 2793,
  'token_str': 'bed'},
 {'score': 0.12845061719417572,
  'sequence': 'i went to school this morning.',
  'token': 2082,
  'token_str': 'school'},
 {'score': 0.06230587139725685,
  'sequence': 'i went to sleep this morning.',
  'token': 3637,
  'token_str': 'sleep'},
 {'score': 0.046952735632658005,
  'sequence': 'i went to class this morning.',
  'token': 2465,
  'token_str': 'class'}]